### ISSUE TITLE
Failed to install provider when executing azd provision

### ISSUE THREAD

**Issue by zedy-wj** [atrakic/fastapi-htmx-azd-template#5]
**Describe the issue:**
When executing the `azd provision` command, terraform failed to install hashicorp/azurerm v3.18.0.
![image](https://user-images.githubusercontent.com/81678720/229783209-a79a7fff-2869-4bbb-bdfa-c8a986722104.png)

**Repro Steps:**

1. azd init
2. azd package
3. azd provision

**Environment:**
OS: Windows
Azd version: azd version 0.7.0-beta.2-pr.2672227 (commit dec4eb2c9f5932d3bd41f7e66b41c775c050ad48)

**Expected behavior:**
Terraform can install all providers successfully.

@rajeshkamal5050, @atrakic  for notification.

**Comment by atrakic** [comment]
Closed with: https://github.com/atrakic/fastapi-htmx-azd-template/commit/b5dc2a7d0249e5897c6fa8f7f6b86019731f8755
